name: submission-test
dependencies:
- base >= 4.7 && < 5
- containers

default-extensions:
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- TypeApplications

library:
  source-dirs: src
  ghc-options:
  - -XSafe
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-unused-imports
  - -fno-warn-type-defaults

tests:
  default: &def
    main:                default.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - submission-test
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - tasty-smallcheck
    - tasty-ant-xml
  # a:
  #   << : *def
  #   main: a.hs

