name: submission-test
dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  ghc-options: -XSafe

tests:
  default: &def
    main:                default.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - submission-test
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - tasty-smallcheck
    - tasty-ant-xml
  a:
    << : *def
    main: a.hs
